# Generated by Django 3.1.7 on 2022-03-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
